
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Albert Contreras
 */
public class ciclos_ejercicio4_calculadora extends javax.swing.JFrame {

    /**
     * Creates new form ciclos_ejercicio4_calculadora
     */
    public ciclos_ejercicio4_calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPanel = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        retirar = new javax.swing.JButton();
        saldo = new javax.swing.JLabel();
        mostrarSaldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco Azteca");
        setResizable(false);

        tituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanel.setText("Bienvenido a tu cuenta de Banco Azteca");

        ingresar.setText("Ingresar dinero");
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
        });

        retirar.setText("Retirar dinero");
        retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirarMouseClicked(evt);
            }
        });

        saldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saldo.setText("Saldo: $");

        mostrarSaldo.setEditable(false);
        mostrarSaldo.setText("0");
        mostrarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(saldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloPanel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldo)
                    .addComponent(mostrarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresar)
                    .addComponent(retirar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private double saldoActual = 0.0;
    
    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Ingrese el monto a ingresar: ");
        try{
            double cantidad = Double.parseDouble(input);
            if(cantidad < 0){
                JOptionPane.showMessageDialog(null,"El monto debe ser mayor a 0","Advertencia",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            saldoActual += cantidad;
            mostrarSaldo.setText(String.valueOf(saldoActual));
           
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Por favor ingrese un número","Advertencia",JOptionPane.WARNING_MESSAGE);
        }      
    }//GEN-LAST:event_ingresarMouseClicked

    private void retirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirarMouseClicked
        String input = JOptionPane.showInputDialog(null,"Ingrese monto a retirar: ");
        
        try{
            double cantidad = Double.parseDouble(input);
            
            if(cantidad < 0){
                JOptionPane.showMessageDialog(null,"El monto a retirar debe ser mayor a 0","Advertencia",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if(cantidad > saldoActual){
                JOptionPane.showMessageDialog(null,"No puedes retirar un monto mayor a tu saldo actual","Advertencia",JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            saldoActual -= cantidad;
            mostrarSaldo.setText(String.valueOf(saldoActual));
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ingrese un número válido");
        }
    }//GEN-LAST:event_retirarMouseClicked

    private void mostrarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ciclos_ejercicio4_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ciclos_ejercicio4_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ciclos_ejercicio4_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ciclos_ejercicio4_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ciclos_ejercicio4_calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresar;
    private javax.swing.JTextField mostrarSaldo;
    private javax.swing.JButton retirar;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
