
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Albert Contreras
 */
public class Ejercicio4_juego_adivinador extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4_juego_adivinador
     */
    public Ejercicio4_juego_adivinador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JLabel();
        descripcion1 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JLabel();
        jugar = new javax.swing.JButton();
        postgameInformacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("¡Adivina el número!");
        setResizable(false);

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado.setForeground(new java.awt.Color(102, 0, 153));
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("JUEGO DEL ADIVINADOR");

        descripcion1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        descripcion1.setText("La computadora va a generar un número aleatorio entre");

        descripcion2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        descripcion2.setText(" el 1 y el 100 y usted deberá de adivinar cual número es en 5 intentos");

        jugar.setText("Jugar");
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
        });

        postgameInformacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        postgameInformacion.setFocusable(false);
        postgameInformacion.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(descripcion1)
                    .addComponent(descripcion2)
                    .addComponent(jugar))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(postgameInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugar)
                .addGap(18, 18, 18)
                .addComponent(postgameInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked
        try{
            Random random = new Random();
            
            int flag = 1;
            int numIntento = 5;
            int numGenerado = random.nextInt(100) + 1;
            
            postgameInformacion.setText(String.valueOf(numGenerado));
            
            while(numIntento > 0 && flag == 1){
                int numeroIngresado = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese número: "));
                if(numeroIngresado == numGenerado){
                    JOptionPane.showMessageDialog(null, "¡Número adivinado!");
                    break;
                }else{
                    if(numeroIngresado < numGenerado){
                        JOptionPane.showMessageDialog(null, "El número a adivinar es MAYOR al ingresado. Quedan "+numIntento+" intentos");
                    }else{
                        if(numeroIngresado > numGenerado){
                            JOptionPane.showMessageDialog(null, "El número a adivinar es MENOR al ingresado. Quedan "+numIntento+" intentos");
                        }
                    }
                }
                numIntento -= 1;
            }
            
            if(numIntento > 0){
                postgameInformacion.setText("Número encontrado en el intento: "+numIntento);
            }else{
                postgameInformacion.setText("Has perdido. Intentos terminados.");
            }
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
            postgameInformacion.setText("Partida cancelada por el usuario");
        }
    }//GEN-LAST:event_jugarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_juego_adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_juego_adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_juego_adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio4_juego_adivinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4_juego_adivinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcion1;
    private javax.swing.JLabel descripcion2;
    private javax.swing.JLabel encabezado;
    private javax.swing.JButton jugar;
    private javax.swing.JLabel postgameInformacion;
    // End of variables declaration//GEN-END:variables
}
