import java.util.Random;
import javax.swing.JOptionPane;
import java.io.FileWriter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Albert Contreras
 */
public class Ejercicio3_piedra_papel_tijeras extends javax.swing.JFrame {
    
    // "C:\Users\Albert Contreras\Desktop\Nuevo Documento de texto.txt"

    /**
     * Creates new form Ejercicio3_piedra_papel_tijeras
     */
    public Ejercicio3_piedra_papel_tijeras() {
        initComponents();
        try {
            historialFile = new FileWriter("C:\\Users\\Albert Contreras\\Desktop\\historial.txt", true); // Abre el archivo en modo de añadir (append)
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo de historial", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        encabezado = new javax.swing.JLabel();
        piedra = new javax.swing.JRadioButton();
        papel = new javax.swing.JRadioButton();
        tijeras = new javax.swing.JRadioButton();
        confirmarOp = new javax.swing.JButton();
        jugadorLetrero = new javax.swing.JLabel();
        jugadorMostrarOpcion = new javax.swing.JTextField();
        cpuLetrero = new javax.swing.JLabel();
        cpuMostrarOpcion = new javax.swing.JTextField();
        victoriasLetrero = new javax.swing.JLabel();
        derrotasLetrero = new javax.swing.JLabel();
        empatesLetreros = new javax.swing.JLabel();
        mostrarVictorias = new javax.swing.JTextField();
        mostrarDerrotas = new javax.swing.JTextField();
        mostrarEmpates = new javax.swing.JTextField();
        rondaLetrero = new javax.swing.JLabel();
        mostrarRondas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piedra, papel o tijeras");

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado.setForeground(new java.awt.Color(0, 102, 102));
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("+ - - PIEDRA, PAPEL O TIJERA - - +");

        opciones.add(piedra);
        piedra.setText("Piedra");

        opciones.add(papel);
        papel.setText("Papel");

        opciones.add(tijeras);
        tijeras.setText("Tijeras");

        confirmarOp.setText("Confirmar opción");
        confirmarOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarOpMouseClicked(evt);
            }
        });

        jugadorLetrero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jugadorLetrero.setText("JUGADOR: ");

        jugadorMostrarOpcion.setEditable(false);
        jugadorMostrarOpcion.setFocusable(false);

        cpuLetrero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cpuLetrero.setText("CPU:");

        cpuMostrarOpcion.setEditable(false);
        cpuMostrarOpcion.setFocusable(false);

        victoriasLetrero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        victoriasLetrero.setForeground(new java.awt.Color(51, 153, 0));
        victoriasLetrero.setText("VICTORIAS: ");

        derrotasLetrero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        derrotasLetrero.setForeground(new java.awt.Color(204, 0, 51));
        derrotasLetrero.setText("DERROTAS:");

        empatesLetreros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empatesLetreros.setForeground(new java.awt.Color(0, 102, 204));
        empatesLetreros.setText("EMPATES:");

        mostrarVictorias.setEditable(false);
        mostrarVictorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mostrarVictorias.setFocusable(false);

        mostrarDerrotas.setEditable(false);
        mostrarDerrotas.setFocusable(false);

        mostrarEmpates.setEditable(false);
        mostrarEmpates.setFocusable(false);

        rondaLetrero.setText("Número de ronda:");

        mostrarRondas.setEditable(false);
        mostrarRondas.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(confirmarOp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jugadorLetrero)
                                .addGap(1, 1, 1)
                                .addComponent(jugadorMostrarOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cpuLetrero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cpuMostrarOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(piedra)
                                .addGap(47, 47, 47)
                                .addComponent(papel)
                                .addGap(51, 51, 51)
                                .addComponent(tijeras)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(victoriasLetrero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(derrotasLetrero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empatesLetreros, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarVictorias, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarDerrotas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rondaLetrero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarRondas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piedra)
                    .addComponent(papel)
                    .addComponent(tijeras))
                .addGap(18, 18, 18)
                .addComponent(confirmarOp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugadorLetrero)
                    .addComponent(jugadorMostrarOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpuLetrero)
                    .addComponent(cpuMostrarOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(victoriasLetrero)
                    .addComponent(mostrarVictorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(derrotasLetrero)
                    .addComponent(mostrarDerrotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empatesLetreros)
                    .addComponent(mostrarEmpates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rondaLetrero)
                    .addComponent(mostrarRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    int victorias = 0, empates = 0, derrotas  = 0, rondas = 1;
    FileWriter historialFile;
    
    private void confirmarOpMouseClicked(java.awt.event.MouseEvent evt) {                                         
        try{
            
            Random random = new Random();
            
             int cpuOpcion = random.nextInt(3) + 1;
                      
            String opcionLetrero = "", cpuOpcionLetrero = "";
            
            if((piedra.isSelected() && cpuOpcion == 1) || (papel.isSelected() && cpuOpcion == 2) || (tijeras.isSelected() && cpuOpcion == 3)){
                empates += 1;
                JOptionPane.showMessageDialog(null, "¡Empate! :0");
            }else{
                if((piedra.isSelected() && cpuOpcion == 2) || (papel.isSelected() && cpuOpcion == 3) || (tijeras.isSelected() && cpuOpcion == 1)){
                    derrotas += 1;
                    JOptionPane.showMessageDialog(null, "¡Derrota! :(");
                }else{
                    if((piedra.isSelected() && cpuOpcion == 3)|| (papel.isSelected() && cpuOpcion == 1) || (tijeras.isSelected() && cpuOpcion == 2)){
                        victorias += 1;
                        JOptionPane.showMessageDialog(null, "¡Victoria! :D");
                    }
                }
            }
            
            if (piedra.isSelected()) {
                jugadorMostrarOpcion.setText("Piedra");
            } else if (papel.isSelected()) {
                jugadorMostrarOpcion.setText("Papel");
            } else if (tijeras.isSelected()) {
                jugadorMostrarOpcion.setText("Tijeras");
            }


            switch(cpuOpcion){
                case 1:
                    cpuMostrarOpcion.setText("Piedra");
                    break;
                case 2:
                    cpuMostrarOpcion.setText("Papel");
                    break;
                case 3:
                    cpuMostrarOpcion.setText("Tijeras");
                    break;
                default:
                    cpuMostrarOpcion.setText("");
            }
            
            mostrarVictorias.setText(String.valueOf(victorias));
            mostrarDerrotas.setText(String.valueOf(derrotas));
            mostrarEmpates.setText(String.valueOf(empates));
            mostrarRondas.setText(String.valueOf(rondas));
            
            historialFile.write(String.format("Ronda %d: Victorias=%d, Derrotas=%d, Empates=%d%n", rondas, victorias, derrotas, empates));
            historialFile.flush();
            
            rondas++;
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio3_piedra_papel_tijeras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio3_piedra_papel_tijeras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton confirmarOp;
    private javax.swing.JLabel cpuLetrero;
    private javax.swing.JTextField cpuMostrarOpcion;
    private javax.swing.JLabel derrotasLetrero;
    private javax.swing.JLabel empatesLetreros;
    private javax.swing.JLabel encabezado;
    private javax.swing.JLabel jugadorLetrero;
    private javax.swing.JTextField jugadorMostrarOpcion;
    private javax.swing.JTextField mostrarDerrotas;
    private javax.swing.JTextField mostrarEmpates;
    private javax.swing.JTextField mostrarRondas;
    private javax.swing.JTextField mostrarVictorias;
    private javax.swing.ButtonGroup opciones;
    private javax.swing.JRadioButton papel;
    private javax.swing.JRadioButton piedra;
    private javax.swing.JLabel rondaLetrero;
    private javax.swing.JRadioButton tijeras;
    private javax.swing.JLabel victoriasLetrero;
    // End of variables declaration                   
}
