
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Albert Contreras
 */
public class Ejercicio2_area_perimetro extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2_area_perimetro
     */
    public Ejercicio2_area_perimetro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        encabezado = new javax.swing.JLabel();
        areaRectangulo = new javax.swing.JRadioButton();
        perimetroRectangulo = new javax.swing.JRadioButton();
        areaCirculo = new javax.swing.JRadioButton();
        perimetroCirculo = new javax.swing.JRadioButton();
        calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de perímetros y áreas");
        setResizable(false);

        encabezado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("+ - - Calculadora de área y perímetro - - +");

        opciones.add(areaRectangulo);
        areaRectangulo.setText("Calcular área de un rectangulo");

        opciones.add(perimetroRectangulo);
        perimetroRectangulo.setText("Calcular perímetro de un rectangulo");

        opciones.add(areaCirculo);
        areaCirculo.setText("Calcular área de un círculo");

        opciones.add(perimetroCirculo);
        perimetroCirculo.setText("Calcular perímetro de un círculo");

        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(areaRectangulo)
                    .addComponent(areaCirculo)
                    .addComponent(perimetroCirculo)
                    .addComponent(perimetroRectangulo))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(calcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(encabezado)
                .addGap(18, 18, 18)
                .addComponent(areaRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perimetroRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaCirculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perimetroCirculo)
                .addGap(18, 18, 18)
                .addComponent(calcular)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked
        try{
            
            double area, perimetro;
            
            if(areaRectangulo.isSelected()){
                double base = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese base del rectangulo"));
                double altura = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese la altura del rectangulo"));
                
                area = base * altura;
                
                JOptionPane.showMessageDialog(null, "El área del rectangulo es de: " + area);
                       
            }else{
                if(perimetroRectangulo.isSelected()){
                    double base = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese base del rectangulo"));
                    double altura = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese la altura del rectangulo"));
                    
                    perimetro = (2 * base) + (2 * altura);
                    
                    JOptionPane.showMessageDialog(null, "El perímetro del rectangulo es de: " + perimetro);
                }else{
                    if(areaRectangulo.isSelected()){
                        double radio = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese radio del circulo"));
                        
                        area = (Math.pow(radio, 2))*3.1416;
                        
                        JOptionPane.showMessageDialog(null, "El área del círculo es de: " + area);   
                    }else{
                        if(perimetroCirculo.isSelected()){
                            double radio = Double.parseDouble(JOptionPane.showInputDialog(null, "Ingrese radio del circulo"));
                            
                            perimetro = radio * 2 * 3.1416;
                            
                            JOptionPane.showMessageDialog(null, "El perímetro del círculo es de: " + perimetro);
                        }
                    }
                }
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ingrese un número", "Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_calcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2_area_perimetro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2_area_perimetro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton areaCirculo;
    private javax.swing.JRadioButton areaRectangulo;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel encabezado;
    private javax.swing.ButtonGroup opciones;
    private javax.swing.JRadioButton perimetroCirculo;
    private javax.swing.JRadioButton perimetroRectangulo;
    // End of variables declaration//GEN-END:variables
}
